import turtle
t = turtle.Turtle()
t.speed(0) # 1:slowest, 3:slow, 5:normal, 10:fast, 0:fastest
t.ht()
t.down()
t.color("black","green")
t.begin_fill()
t.forward(100)
for i in range(30):
  t.forward(1)
  t.right(3)
t.forward(50)
for i in range(30):
  t.forward(1)
  t.right(3)
t.left(90)
t.forward(20)
t.right(135)
t.forward(28)
t.left(45)
t.forward(80)
for i in range(30):
  t.forward(1)
  t.right(3)
t.forward(50)
for i in range(30):
  t.forward(1)
  t.right(3)
t.end_fill()
t.up()
t.right(45)
t.forward(20)
t.color("black","red")
t.left(150)
t.down()
t.begin_fill()
t.forward(50)
for i in range(120):
  t.forward(1)
  t.left(2)
t.forward(50)
t.end_fill()
t.up()
t.left(135)
t.forward(55)
t.color("black","white")
t.down()
t.begin_fill()
for i in range(90):
  t.forward(1)
  t.left(4)
t.end_fill()
t.up()
t.color("yellow")
t.width(5)
t.setpos(-18,-55)
t.right(75)
t.down()
t.forward(75)
t.up()
t.setpos(-0,-87)
t.down()
t.forward(120)
t.up()
t.setpos(60,-87)
t.down()
t.forward(80)
t.up()
t.setpos(112,-82)
t.left(90)
t.down()
t.forward(110)
t.up()
t.setpos(60,-87)
t.down()
t.forward(105)
